### ISSUE TITLE
Retrieve compounds by name from CHEMBL

### ISSUE THREAD

**Issue by ahgough** [UPDDI/mps-database-server#268]
It would be useful to search by name rather than CHEMBLID.  One problem is the name may not be unique.  In that case the software could return a list for the user to choose from.  For example, if I search CHEMBL for menadione I find 3 IDs with the listed synonyms:
590               Menaphthone  Menaphthene  Menadione
1550             Phytonadione  Vitamin K1  Phytomenadione
1159684       Menadione Sulfurous Acid    Menadione Sodium Bisulfite 
Presenting a list, allowing the user to choose one of these based on synonyms would be good.

**Comment by Luke-Malchow-Bergenthal** [comment]
Retrieving a ChEMBL ID (or list of ChEMBL IDs) with a name would be, to my understanding, difficult to achieve.

Bioservices (the library we are using to collect ChEMBL data) does not offer any means of doing this and ChEMBL uses a POST-based search (that is, I can not access the results of a search using a URL as is the case with something like: https://www.ncbi.nlm.nih.gov/pccompound?term=aspirin).

As you suggested, we could have a popup window with the full ChEMBL website that will return the selected ChEMBL ID. Otherwise, and this is certainly more convoluted, we could perform a search on a different website (say, PubChem) and extract a ChEMBL ID from there.

**Comment by Luke-Malchow-Bergenthal** [comment]
An interface for searching ChEMBL while remaining on the website will be added as part of pull request https://github.com/UPDDI/mps-database-server/pull/345.

**Comment by Luke-Malchow-Bergenthal** [comment]
Available on production as of https://github.com/UPDDI/mps-database-server/commit/7baeabdf8e7fe41db717951826d05421ec3beeb1
